### ISSUE TITLE
Workaround for compilation problem

### ISSUE THREAD

**Issue by davidfowl** [thiennn/trymodular#3]
The problem is a known issue with 1.0.0 and how MVC finds compilation assemblies for class libraries in particular. You can workaround the issue by adding the modules assemblies to the list of compilation assemblies directly.

Replace https://github.com/thiennn/trymodular/blob/master/Modular/src/Modular.WebHost/Startup.cs#L71 with the following:

``` C#
var mvcBuilder = services.AddMvc()
        .AddRazorOptions(o =>
        {
            foreach (var module in modules)
            {
                o.AdditionalCompilationReferences.Add(MetadataReference.CreateFromFile(module.Assembly.Location));
            }
});
```

**Comment by thiennn** [comment]
Yeah, it works
